import type { Metadata } from "next";
import "~/globals.css";

import PrelineScriptWrapper from "@/components/PrelineScriptWrapper"; //Preline UI
import WelcomeScreen from "@/components/WelcomeAnimation";
import { quicksand, zenKakuGothicAntique } from "@/fonts/Fonts"; //Googleフォント

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html
            lang="ja"
            className={`${quicksand.className} ${zenKakuGothicAntique.className}`}
        >
            <body
                className="flex flex-col min-h-screen
            text-[var(--color-text)] dark:text-[var(--color-dark-text)]
            bg-[var(--color-secondary)] dark:bg-[var(--color-dark-secondary)]"
            >
                {children}
                <WelcomeScreen />
            </body>

            <PrelineScriptWrapper />
        </html>
    );
}
